### ISSUE TITLE
how validate in react-boostrap form validated

### ISSUE THREAD

**Issue by fturiot** [bl00mber/react-phone-input-2#381]
HI,
When phone is invalid (isValid = false) the component is red but impossible in form is not considered invalis
how integrate this component in form validation ?

thanks for all

**Comment by multiwebinc** [comment]
This component mimics Bootstrap's style, but unfortunately, it does not play well with Bootstrap in this sense since it overrides a few of Bootstrap's values, particularly those to do with invalid form types. Even the apparently "plain" version applies several styles to the <input> element that people may not want, or will need to then override. In my opinion, "plain" should be used for the bare minimum styling, like the necessary positioning, padding or margins. Any additional colors, backgrounds, borders, etc applied to the <input> element are unnecessary. 

```less
  .form-control {
    position: relative;
    font-size: 14px;
    letter-spacing: .01rem;
    margin-top: 0 !important;
    margin-bottom: 0 !important;
    padding-left: 48px;
    margin-left: 0;
    background: #FFFFFF;
    border: 1px solid #CACACA;
    line-height: 25px;
    height: 35px;
    width: 300px;
    outline: none;
    &.invalid-number {
      border: 1px solid #d79f9f;
      background-color: #FAF0F0;
      border-left-color: #cacaca;
      &:focus {
        border: 1px solid #d79f9f;
        border-left-color: #cacaca;
        background-color: #FAF0F0;
      }
    }
  }
```

from plain.less should be reduced to simply:

```less
  .form-control {
    position: relative;
    margin-top: 0 !important;
    margin-bottom: 0 !important;
    padding-left: 48px;
  }
```

Everything else should be left up to the user to style or allow styling using a CSS framework (like Bootstrap), which, in most cases, will already be installed anyway if that's the look people are going for. That's why it's called "plain".

This is the CSS I added to get it to play nicely with Bootstrap's `is-invalid` class while using the "plain" version:

```css
.react-tel-input .form-control {
  width: 100%;
  height: calc(1.5em + .75rem + 2px);
  font-size: 1rem;
}

.react-tel-input .form-control.is-invalid, .was-validated .react-tel-input .form-control:invalid {
  border-color: #dc3545;
  background-color: #fff;
  background-image:url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='none' stroke='%23dc3545' viewBox='0 0 12 12'%3e%3ccircle cx='6' cy='6' r='4.5'/%3e%3cpath stroke-linejoin='round' d='M5.8 3.6h.4L6 6.5z'/%3e%3ccircle cx='6' cy='8.2' r='.6' fill='%23dc3545' stroke='none'/%3e%3c/svg%3e");
  background-repeat: no-repeat;
  background-position: right calc(.375em + .1875rem) center;
  background-size: calc(.75em + .375rem) calc(.75em + .375rem);
}

.react-tel-input .form-control.is-invalid:focus, .was-validated .react-tel-input .form-control:invalid:focus {
  background-color: #fff;
  border-color: #dc3545;
}

.react-tel-input .flag-dropdown {
  top: 1px;
  bottom: 1px;
  left: 1px;
  border-radius: 3px;
}
```
