### ISSUE TITLE
How to change the Label color while click input field

### ISSUE THREAD

**Issue by Kavin-Sunware** [bl00mber/react-phone-input-2#669]
I tried this css:
.my-phone-input:focus + .special-label {
  color: blue;
}

<PhoneInput  inputClass="my-phone-input" />

**Comment by davidha99** [comment]
```css
:has(input:focus) label {
  color: blue;
}
````

**Comment by davidha99** [comment]
```html
<div class="control-group">
    <label class="control-label" for="inputEmail">Firstname</label>
    <div class="controls">
        <input type="text" id="inputEmail" placeholder="Firstname">
    </div>
</div>
````

```css
.control-group:has(input:focus) label{
 color: red;
}
```

You can check this post: [On input focus change color of label. How?](https://stackoverflow.com/questions/21154616/on-input-focus-change-color-of-label-how)
